### ISSUE TITLE
Allow global defaults

### ISSUE THREAD

**Issue by EvanLovely** [aleksip/plugin-data-transform#1]
It would be great if I could use these tools in `data.json`. In particular, I would like to have this in it:

``` json
{
  "attributes": {
    "Attribute()": {
      "class": []
    }
  }
}
```

Otherwise I need to have that same thing in every pattern's sidecar json file so things like this work:

``` twig
{%
  set classes = [
    'block'
  ]
%}
<div{{ attributes.addClass(classes) }}>
  <p>Cool stuff here</p>
</div>
```

Let me know if you'd like me to spin up a sample repo that shows this with more detail; thanks!

**Comment by aleksip** [comment]
@EvanLovely I think I have figured out how to get this working. Hope to have some time to try it out this week.

**Comment by aleksip** [comment]
Looks like this is not possible without changes in `patternlab-php-core`. I have created an [issue](https://github.com/pattern-lab/patternlab-php-core/issues/43) there.

**Comment by aleksip** [comment]
@EvanLovely `dev` branch now has support for global data. Testing it would be much appreciated! Please note the 'Global data and includes' section in the README.

**Comment by aleksip** [comment]
@EvanLovely Looks like @dmolsen just released an official [Data Inheritance Plugin](https://github.com/pattern-lab/plugin-php-data-inheritance). I'll probably remove this feature from Data Transform Plugin in favour of the official plugin if the functionality is identical.

**Comment by aleksip** [comment]
Global data is finally supported in the 1.0.0 release of Data Transform Plugin.
