### ISSUE TITLE
`Include pattern files` more info

### ISSUE THREAD

**Issue by romanovma** [aleksip/plugin-data-transform#14]
Hi, could you please provide more info on how to use `Include pattern files` feature?
It doesn't work for me, may be I do something wrong. 

Where to store the `html` pattern file? Is it relative path to it?
How to put this parameter into twig? `{{ key }}`?

Thank you.

**Comment by aleksip** [comment]
Hi, the `include()`d files should be Twig pattern files or pseudo-pattern data files. The name of the included file should be in standard Pattern Lab [shorthand include syntax](http://patternlab.io/docs/pattern-including.html), and it can be anywhere in the Pattern Lab directory structure. The included file can be added in the respective Twig file using `{{ key }}`.

**Comment by romanovma** [comment]
Thanks a lot!
