### ISSUE TITLE
What does only do?

### ISSUE THREAD

**Issue by mortona42** [aleksip/plugin-data-transform#21]
What does `only: true` do here?

```yaml
{
    "key": {
        "include()": {
            "pattern": "atoms-form-element-label.html",
            "with": {
                "title": "Textfield label"
            },
            "only": true
        }
    }
}
```

**Comment by aleksip** [comment]
Basically the same as if using `include` with `only` in Twig: https://twig.symfony.com/doc/2.x/tags/include.html

Good question, I will try to improve the documentation!

**Comment by aleksip** [comment]
Have now updated the README with this info.
