### ISSUE TITLE
PHP Notice:  Undefined index: XXX in vendor/aleksip/plugin-data-transform/src/aleksip/DataTransformPlugin/DataTransformer.php

### ISSUE THREAD

**Issue by gambry** [aleksip/plugin-data-transform#23]
I've received lot of PHP notices during running `php core/console --generate` as - I believe the condition in [here](https://github.com/aleksip/plugin-data-transform/blob/67b437f439d66aec1ee51ca6b5225fded5b69e0a/src/aleksip/DataTransformPlugin/DataTransformer.php#L82) needs some additional validation, i.e. `isset($dataStore[$key]) && ...`?

**Comment by aleksip** [comment]
Merged your PR, thanks!
