### ISSUE TITLE
Twig extensions loaded through PL 'twigPatternLoader.customize' are not loaded if 'include()' transformer is used

### ISSUE THREAD

**Issue by gambry** [aleksip/plugin-data-transform#24]
I created [this twig extension](https://gitlab.com/gambry/pattern-twig-extension) and provided an autoload for PL using the 'twigPatternLoader.customize'.

The extension is not loaded if the 'include()' data transformer is used. It looks like when 'include()' is used the twig renderer is loaded earlier then needed, which set`Twig_Environment::extensionInitialized` to TRUE when actually things may still be loaded later on.

I tried to dig in to give more details, but didn't have enough time.

I believe the best - probably even long term - solution is to set priority `-99` on subscriber `$this->addListener('twigPatternLoader.customize', 'addNodeVisitor');`. In this way this loader is likely to be loaded as last one, letting other plugins adding or altering twig extensions.

**Comment by gambry** [comment]
> I created [this twig extension](https://gitlab.com/gambry/pattern-twig-extension) and provided an autoload for PL using the 'twigPatternLoader.customize'.
I'm not sure if this is good practice though. The PL documentation doesn't describe what events are for.

However I've seen this practice on other PL plugins providing or altering twig extensions, so better to fix this package as first.

**Comment by aleksip** [comment]
Merged your PR, thanks!
