### ISSUE TITLE
Shorthand partials syntax

### ISSUE THREAD

**Issue by hctom** [aleksip/plugin-data-transform#4]
I just wondered if the shorthand partials syntax for `include()` only works in the format `TYPE-TPLNAMEWITHOUTEXT`?

We are running into problems with this, because we have templates saved like this (to keep the patternlab menu links as short as possible):
- atoms
  - component
    - default.twig
    - xyz.twig
  - another-component
    - default.twig

As you can see, shorthand syntax `atoms-default` would target two different templates. So is this by design (I know templates should normally have the component name as filename), or is there any possibility to target an exact component, even if there is another one with the same template name?

Thanx in advance

**Comment by aleksip** [comment]
The `include()` function basically just uses [Pattern Lab Core](https://github.com/pattern-lab/patternlab-php-core), please open an issue there.

**Comment by hctom** [comment]
For anybody interested, here is the follow up at Pattern Lab Core: https://github.com/pattern-lab/patternlab-php-core/issues/55
