### ISSUE TITLE
Includes in global data don't work

### ISSUE THREAD

**Issue by aleksip** [aleksip/plugin-data-transform#6]
Moved [pattern-lab/edition-php-drupal-standard#19](https://github.com/pattern-lab/edition-php-drupal-standard/issues/19) here as it is about a bug in `plugin-data-transform`.

**Comment by aleksip** [comment]
@ensk Could you try if `"aleksip/plugin-data-transform": "dev-dev"` fixes your problem?

**Comment by ensk** [comment]
It works perfect 
thanks you @aleksip

**Comment by aleksip** [comment]
Great! Thanks for using the plugin and finding and reporting this bug.

I've just released 1.0.1 containing the fix.
