### ISSUE TITLE
what does this repo do?

### ISSUE THREAD

**Issue by MuschPusch** [aleksip/plugin-data-transform#7]
`Pattern Lab core only supports global data files and a pattern-specific data file for the main pattern. This plugin adds pattern-specific data file support for included patterns.`

Could you elaborate a bit more what this repository is doing? It's a dependency of pattern-lab-starter and the edition-php-drupal-standard that's how far i got :)

**Comment by aleksip** [comment]
Hi @MuschPusch, sorry for the late reply. Basically `plugin-data-transform` is a Pattern Lab plugin that was written to make it possible to use unmodified Drupal 8 Twig templates in Pattern Lab. You can find some (now partly outdated) blog posts containing more information at http://www.aleksip.net/.
